defmodule ExClubhouse.Model.StorySlim do
  @moduledoc """
  Story slim model
  """

  alias ExClubhouse.Model

  @type t :: %__MODULE__{
          app_url: binary(),
          archived: boolean(),
          blocked: boolean(),
          blocker: boolean(),
          comment_ids: list(integer()),
          completed: boolean(),
          completed_at: binary() | nil,
          completed_at_override: binary() | nil,
          created_at: binary(),
          deadline: binary() | nil,
          entity_type: binary(),
          epic_id: integer() | nil,
          estimate: integer() | nil,
          external_id: binary() | nil,
          external_tickets: list(Model.ExternalTicket.t()),
          file_ids: list(integer()),
          follower_ids: list(binary()),
          group_mention_ids: list(binary()),
          id: integer(),
          iteration_id: integer() | nil,
          labels: list(Model.Label.t()),
          linked_file_ids: list(integer()),
          member_mention_ids: list(binary()),
          mention_ids: list(binary()),
          moved_at: binary() | nil,
          name: binary(),
          owner_ids: list(binary()),
          position: integer(),
          previous_iteration_ids: list(integer()),
          project_id: integer(),
          requested_by_id: binary(),
          started: binary() | nil,
          started_at: binary() | nil,
          started_at_override: binary() | nil,
          stats: Model.StoryStats.t(),
          story_links: list(Model.TypedStoryLink.t()),
          story_type: binary(),
          task_ids: list(integer()),
          updated_at: binary() | nil,
          workflow_state_id: integer()
        }

  defstruct app_url: nil,
            archived: nil,
            blocked: nil,
            blocker: nil,
            comment_ids: [],
            completed: nil,
            completed_at: nil,
            completed_at_override: nil,
            created_at: nil,
            deadline: nil,
            entity_type: nil,
            epic_id: nil,
            estimate: nil,
            external_id: nil,
            external_tickets: [],
            file_ids: [],
            follower_ids: [],
            group_mention_ids: [],
            id: nil,
            iteration_id: nil,
            labels: [],
            linked_file_ids: [],
            member_mention_ids: [],
            mention_ids: [],
            moved_at: nil,
            name: nil,
            owner_ids: [],
            position: nil,
            previous_iteration_ids: [],
            project_id: nil,
            requested_by_id: nil,
            started: nil,
            started_at: nil,
            started_at_override: nil,
            stats: nil,
            story_links: [],
            story_type: nil,
            task_ids: [],
            updated_at: nil,
            workflow_state_id: nil
end
